name: Pytest + flake 8

on:
push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]  # Replace 3.9 with your development version

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pytest flake8
        pip install -r requirements.txt
    - name: Run flake8
      run: flake8 .
    - name: Run pytest
      run: pytest
